# ssh 
# server project dir
# server virtualenv dir
env:
    project: foobar
    user: root
    webserver_software: nginx # or apache
    db_software: postgresql # or mysql
    path: /home/%(user)s/public_html/%(project)s
    live_url: http://foobar.com

# deploy_type is for the kind of server environment it is
#   - shell (default, for the common use-case)
#   - dotcloud (for a dotcloud deployment)
#   - heroku (for a heroku deployment)
#   - epio (for an ep.io deployment)
#   - gondor (for a gondor.io deployment)
# stage is for the step of deployment you're on
#   - prod (default, production live servers)
#   - staging
#   - dev
# os is the operating system of the machine
#   - ubuntu (default)
#   - debian
#   - centos
#   - fedora
#   - rhel
#   - osx
# port is implied to be 22 unless otherwise specified (for ssh)
# WARNING: DO NOT place your local machine here. Run at your own risk.
servers:
    www:
        ip: 1.2.3.4
        os: ubuntu

roles:
    app:
        - www
    db:
        - www
    static:
        - www
